//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDCliente.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clientes
    {
        public int NumeroIdentificacion { get; set; }
        [Required]
        public string Nombres { get; set; }
        [Required]
        public int IdTipoIdentificacion { get; set; }
        [Required]
        public string Correo { get; set; }
        [Required]
        public string Celular { get; set; }
        [Required]
        public string Direccion { get; set; }
        [Required]
        public string DireccionDeInstalacion { get; set; }
        [Required]
        public Nullable<bool> Activo { get; set; }
    
        public virtual TipoIdentificacion TipoIdentificacion { get; set; }
    }
}
